logging:
  level:
    org: WARN
    com.dqr.kotlin-ws: INFO

server:
  port: 8080

spring:
  jackson:
    serialization:
      indent_output: true
  jpa:
    show-sql: true
  resources:
    static-locations:
    - file:/src/main/resources/public/
    - classpath:/public/
    
dqr:
  datasources:
    my-kotlin-ws-ds:
      url: "jdbc:h2:mem:my-kotlin-placeholder-ws;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE"

browser:
  startup: true
  host: localhost.ldschurch.org
  path: ${dqr.api-path}